#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/launch.sh --forest &
#wmname LG3D 

bspc monitor DVI-I-0 -d "0"
bspc monitor DP-1    -d "1" "2" "3" "4" "5" 

bspc config border_width        2 
bspc config window_gap          8

# some extra top space for bar
bspc config top_padding    0
bspc config right_padding  0 
bspc config left_padding   0
bspc config bottom_padding 0

# colors
bspc config normal_border_color "#616161"
bspc config focused_border_color "#84909D"


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Sxiv state=floating
bspc rule -a Gimp-2.10 desktop='5' follow=on
bspc rule -a Firefox desktop='2' follow=on
bspc rule -a TelegramDesktop desktop='4' follow=on
bspc rule -a jetbrains-idea-ce desktop='1' follow=on
bspc rule -a Gnome-calculator state=floating
